version: "3.7"

services:
  docuprinter:
    container_name: docuprinter
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    ports:
      - "2305:2305"
